tsEnableAutoTypes: false

packageExtensions:
  "eslint-plugin-perfectionist@*":
    peerDependencies:
      typescript: "*"
  "@stylistic/eslint-plugin@*":
    peerDependencies:
      typescript: "*"
