name: publish
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup-yarn.yaml
      - run: yarn build-release
      - run: yarn npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
