name: test
on:
  push:
    branches-ignore:
      - 'save*'
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup-yarn.yaml
      - run: yarn test-release
